import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner'
import { fetchNasaData } from '../lib/fetch_nasa_data'
import styles from '../styles/Home.module.css'


export async function getStaticProps(context) {
  const coffeeStores = await fetchNasaData()

  return {
    props: {
      coffeeStores,
    },
  };
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner
        
      />

      <main >
      {/* {coffeeStores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Stores near me</h2>

            <div className={styles.cardLayout}>
              {coffeeStores.map((coffeeStore) => (
                <Card
                  key={coffeeStore.id}
                  name={coffeeStore.name}
                  imgUrl={
                    coffeeStore.imgUrl ||
                    "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                  }
                  href={`/coffee-store/${coffeeStore.id}`}
                  className={styles.card}
                />
              ))}
            </div>
          </div>
        )} */}
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
